name: android-za
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Build ZA APK & AAB (release)
        working-directory: TalaaZAApp/android
        run: |
          chmod +x gradlew || true
          ./gradlew assembleRelease bundleRelease --stacktrace --info

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: talaaZA-artifacts
          path: |
            TalaaZAApp/android/app/build/outputs/apk/release/*.apk
            TalaaZAApp/android/app/build/outputs/bundle/release/*.aab
